export const initFormList = [
  {
    id: 1,
    title: "Personal information",
    completed: false,
  },
  {
    id: 2,
    title: "Work Experience",
    completed: false,
  },
  {
    id: 3,
    title: "About the company",
    completed: false,
  },
];

export const initFormData = {
  1: {
    multipleForm: false,
    formList: [
      {
        id: 1,
        formTitle: "",
        value: "",
        errorMessage: "",
        data: [
          {
            id: 1,
            view: "input-text",
            required: true,
            value: "",
            label: "Full Name",
            labelDescription: "",
            maxLength: 100,
            errorMessage: "",
          },
          {
            id: 2,
            view: "input-date",
            required: true,
            value: "",
            label: "Date of birth",
            labelDescription: "",
            errorMessage: "",
          },
          {
            id: 3,
            view: "input-selector",
            required: true,
            value: "",
            label: "City",
            labelDescription: "",
            selectData: [
              "HaNoi",
              "ThanhHoa",
              "NgheAn",
              "HungYen",
              "NgheAn",
              "NgheAn",
              "NgheAn",
              "NgheAn",
              "NgheAn",
              "NgheAn",
            ],
            errorMessage: "",
          },
          {
            id: 4,
            view: "input-searchBar",
            required: false,
            value: [],
            label: "Positions",
            labelDescription: "You can select multiple position",
            searchData: [
              { id: 1, name: "fontEnd developer" },
              { id: 2, name: "backend developer" },
              { id: 3, name: "business analyst" },
              { id: 4, name: "project manager" },
              { id: 5, name: "devOp" },
              { id: 6, name: "marketing" },
            ],
            errorMessage: "",
          },
          {
            id: 5,
            view: "input-textarea",
            required: false,
            value: "",
            label: "Description",
            labelDescription: "",
            maxLength: 1000,
            errorMessage: "",
          },
          {
            id: 6,
            view: "input-dropDownFile",
            required: false,
            value: [],
            label: "Avatar",
            labelDescription: "",
            maxSize: 10485760,
            errorMessage: "",
          },
        ],
      },
    ],
  },
  2: {
    multipleForm: true,
    formList: [
      {
        id: 1,
        formTitle: "company",
        errorMessage: "",
        value: "",
        data: [
          {
            id: 1,
            view: "input-text",
            required: true,
            value: "",
            label: "previous position",
            labelDescription: "",
            errorMessage: "",
          },
          {
            id: 2,
            view: "input-fromToDatePicker",
            required: true,
            value: "",
            label: "work-time",
            labelDescription: "",
            errorMessage: "",
          },
          {
            id: 3,
            view: "input-textarea",
            required: false,
            value: "",
            label: "Work description",
            labelDescription: "",
            maxLength: 5000,
            errorMessage: "",
          },
        ],
      },
    ],
  },
  3: {
    multipleForm: false,
    formList: [
      {
        id: 1,
        formTitle: "",
        value: "",
        errorMessage: "",
        data: [
          {
            id: 1,
            view: "input-textarea",
            required: true,
            value: "",
            label: "Why do you want to work here",
            maxLength: 1000,
            errorMessage: "",
          },
          {
            id: 2,
            view: "input-number",
            required: true,
            value: "",
            label: "desired salary",
            maxLength: 10,
            currency: "VND",
            errorMessage: "",
          },
        ],
      },
    ],
  },
};
